services:
  - type: web
    name: Autonomous_research_agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: NOTION_API_KEY
        sync: false
      - key: NOTION_DB_ID
        sync: false
